# Generated by Django 5.1.3 on 2025-05-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0002_rename_category_categories_rename_post_posts_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="Posts",
            new_name="Post",
        ),
        migrations.RenameModel(
            old_name="Subscribers",
            new_name="Subscriber",
        ),
        migrations.RenameModel(
            old_name="Categories",
            new_name="Tag",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
