# Generated by Django 5.1.3 on 2025-05-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="facebook",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="twitter",
            field=models.IntegerField(default=0),
        ),
    ]
