# Generated by Django 5.1.3 on 2025-05-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("www", "0006_post_facebook_post_twitter"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.IntegerField(default=0),
        ),
    ]
